/**
 * Protobuf-backed CallBodyCodec impl. Uses pbjs static-module codegen
 * (no reflective JIT, no runtime .proto parsing). One Layer:
 *
 *   ProtobufLayer — encodes `Call` against `src/call/codec/call.proto`.
 *
 * Wire schema: `sipjsserver.call.Call` in `call.proto`. The static module
 * is committed alongside the .proto file (`call.proto.gen.cjs`) and is
 * regenerated by hand whenever `call.proto` changes:
 *
 *   npx -p protobufjs-cli@1.1.3 pbjs --target static-module --keep-case \
 *       --wrap commonjs --out src/call/codec/call.proto.gen.cjs \
 *       src/call/codec/call.proto
 *
 * Pin to pbjs 1.1.3: pbjs 2.x emits `reader.tag()` calls that aren't on
 * the `protobufjs/minimal` Reader prototype, so the generated code only
 * runs if the full `protobufjs` is also loaded. 1.1.3 emits
 * `reader.uint32()` which works against minimal.
 *
 * Per ADR-0011: a codec change is a fresh-cluster event (drain + FLUSHDB +
 * redeploy). The schema therefore does not need backwards-compatible field
 * tags across releases — but tags MUST be append-only within a release.
 *
 * Field translations between the Call schema and the proto:
 *   - `_topology`        ↔ `topology`         (proto identifiers can't lead with `_`)
 *   - `features`         ↔ `featuresJson`     (closed union, structurally serialised as JSON)
 *   - `policyUpdateHeaders` ↔ `policyUpdateHeadersJson`
 *   - `Call.ext` / `Leg.ext` ↔ `extJson`      (opaque per-service slices, JSON;
 *      transfer state now rides inside `ext` as the transfer service slice)
 *   - `ActiveRule.params`     ↔ `paramsJson`  (+ `paramsPresent`)
 *   - `RuleStateEntry.state`  ↔ `stateJson`   (+ `statePresent`)
 *   - `pendingInviteTxn`      ↔ `pendingInviteTxnJson` (best-effort handle)
 *
 * Optional fields with null distinct from absent (e.g. `activePeer`,
 * `billingContext`, `policyUpdateBody`, `remoteCSeq`) carry an explicit
 * `*IsNull` flag. Proto3 cannot distinguish absent from null, so the
 * null bit is on the wire as a separate boolean.
 *
 * Optional repeated fields (e.g. `aLegPendingVias`, `activeRules`,
 * `ruleState`, `terminatingRefreshLegs`) carry an explicit `*Present`
 * flag because `Schema.optional(Schema.Array(_))` admits three states
 * (absent / empty / populated) and proto3 collapses absent and empty.
 */

import { Effect, Layer } from "effect"
import { createRequire } from "node:module"
import { CallBodyCodec, type CallBodyCodecApi } from "./CallBodyCodec.js"
import type { ActiveRule, Call, Dialog, Leg, RuleStateEntry } from "../CallModel.js"

const requireCjs = createRequire(import.meta.url)
const staticProto = requireCjs("./call.proto.gen.cjs") as {
  readonly sipjsserver: { readonly call: { readonly Call: ProtoMessageType } }
}

interface ProtoMessageType {
  readonly create: (props: unknown) => unknown
  readonly encode: (msg: unknown) => { finish: () => Uint8Array }
  readonly decode: (buf: Uint8Array) => unknown
  readonly toObject: (
    msg: unknown,
    options: { bytes: typeof Buffer; defaults?: boolean; arrays?: boolean },
  ) => Record<string, unknown>
}

const CallProto = staticProto.sipjsserver.call.Call

// ---------------------------------------------------------------------------
// Encode: Call → proto-friendly plain object
// ---------------------------------------------------------------------------

const encodeDialog = (d: Dialog): unknown => {
  const { remoteCSeq, ...rest } = d.ext
  return {
    sip: { ...d.sip, routeSet: [...d.sip.routeSet] },
    ext: {
      ...rest,
      remoteCSeq: remoteCSeq === null ? undefined : remoteCSeq,
      remoteCSeqIsNull: remoteCSeq === null ? true : undefined,
      pendingInviteTxnJson:
        d.ext.pendingInviteTxn === undefined
          ? undefined
          : JSON.stringify(d.ext.pendingInviteTxn),
      pendingInviteTxn: undefined,
      inboundPendingRequests: d.ext.inboundPendingRequests.map((p) => ({
        ...p,
        sourceVias: [...p.sourceVias],
      })),
    },
  }
}

const encodeLeg = (l: Leg): unknown => ({
  ...l,
  dialogs: l.dialogs.map(encodeDialog),
  pendingInviteTxnJson:
    l.pendingInviteTxn === undefined ? undefined : JSON.stringify(l.pendingInviteTxn),
  pendingInviteTxn: undefined,
  extJson: l.ext === undefined ? undefined : JSON.stringify(l.ext),
  ext: undefined,
})

const encodeActiveRule = (r: ActiveRule): unknown => ({
  id: r.id,
  active: r.active,
  paramsPresent: r.params !== undefined,
  paramsJson: r.params === undefined ? undefined : JSON.stringify(r.params),
})

const encodeRuleState = (r: RuleStateEntry): unknown => ({
  ruleId: r.ruleId,
  statePresent: r.state !== undefined,
  stateJson: r.state === undefined ? undefined : JSON.stringify(r.state),
})

const toProtoObject = (call: Call): Record<string, unknown> => {
  const out: Record<string, unknown> = {
    callRef: call.callRef,
    aLeg: encodeLeg(call.aLeg),
    bLegs: call.bLegs.map(encodeLeg),
    aLegInvite: {
      ...call.aLegInvite,
      headers: call.aLegInvite.headers.map((h) => ({ ...h })),
    },
    limiterEntries: call.limiterEntries.map((e) => ({ ...e })),
    timers: call.timers.map((t) => ({ ...t })),
    cdrEvents: call.cdrEvents.map((e) => ({ ...e })),
    state: call.state,
    createdAt: call.createdAt,
    tagMap: call.tagMap.map((m) => ({ ...m })),

    activePeer: call.activePeer === null ? undefined : call.activePeer,
    activePeerIsNull: call.activePeer === null,
  }

  if (call.callbackContext !== undefined) out.callbackContext = call.callbackContext
  if (call.billingContext !== undefined) {
    if (call.billingContext === null) {
      out.billingContextIsNull = true
    } else {
      out.billingContext = call.billingContext
    }
  }
  if (call.aLegPendingVias !== undefined) {
    out.aLegPendingVias = [...call.aLegPendingVias]
    out.aLegPendingViasPresent = true
  }
  if (call.aLegPendingCSeq !== undefined) out.aLegPendingCSeq = call.aLegPendingCSeq
  if (call.traceId !== undefined) out.traceId = call.traceId
  if (call.rootSpanId !== undefined) out.rootSpanId = call.rootSpanId
  if (call.sampled !== undefined) out.sampled = call.sampled
  if (call.workerIndex !== undefined) out.workerIndex = call.workerIndex
  if (call._topology !== undefined) out.topology = { ...call._topology }
  if (call.emergency !== undefined) out.emergency = call.emergency

  if (call.features !== undefined) out.featuresJson = JSON.stringify(call.features)
  if (call.policyUpdateHeaders !== undefined)
    out.policyUpdateHeadersJson = JSON.stringify(call.policyUpdateHeaders)
  if (call.policyUpdateBody !== undefined) {
    if (call.policyUpdateBody === null) {
      out.policyUpdateBodyIsNull = true
    } else {
      out.policyUpdateBody = call.policyUpdateBody
    }
  }
  if (call.activeRules !== undefined) {
    out.activeRules = call.activeRules.map(encodeActiveRule)
    out.activeRulesPresent = true
  }
  if (call.ruleState !== undefined) {
    out.ruleState = call.ruleState.map(encodeRuleState)
    out.ruleStatePresent = true
  }
  if (call.ext !== undefined) out.extJson = JSON.stringify(call.ext)
  if (call.messageCount !== undefined) out.messageCount = call.messageCount
  if (call.terminatingRefreshLegs !== undefined) {
    out.terminatingRefreshLegs = [...call.terminatingRefreshLegs]
    out.terminatingRefreshLegsPresent = true
  }

  return out
}

// ---------------------------------------------------------------------------
// Decode: proto plain object → Call
// ---------------------------------------------------------------------------

interface ProtoDialog {
  sip: {
    callId: string
    localTag: string
    remoteTag: string
    localUri: string
    remoteUri: string
    remoteTarget: string
    localCSeq: number
    routeSet: string[]
  }
  ext: {
    remoteCSeq?: number
    remoteCSeqIsNull?: boolean
    inboundPendingRequests: unknown[]
    ackBranch?: string
    pendingInviteTxnJson?: string
    cachedSdp?: Buffer
  }
}

interface ProtoLeg {
  legId: string
  callId: string
  fromTag: string
  source: { address: string; port: number }
  state: string
  disposition: string
  dialogs: ProtoDialog[]
  noAnswerTimeoutSec?: number
  byeDisposition?: string
  localUri?: string
  remoteUri?: string
  inviteRequestUri?: string
  pendingInviteTxnJson?: string
  extJson?: string
}

const decodeDialog = (d: ProtoDialog): Dialog => ({
  sip: d.sip,
  ext: {
    remoteCSeq: d.ext.remoteCSeqIsNull === true ? null : d.ext.remoteCSeq ?? null,
    inboundPendingRequests: d.ext.inboundPendingRequests as Dialog["ext"]["inboundPendingRequests"],
    ...(d.ext.ackBranch !== undefined ? { ackBranch: d.ext.ackBranch } : {}),
    ...(d.ext.cachedSdp !== undefined ? { cachedSdp: d.ext.cachedSdp } : {}),
    ...(d.ext.pendingInviteTxnJson !== undefined
      ? {
          pendingInviteTxn: JSON.parse(
            d.ext.pendingInviteTxnJson,
          ) as Dialog["ext"]["pendingInviteTxn"],
        }
      : {}),
  },
})

const decodeLeg = (l: ProtoLeg): Leg => ({
  legId: l.legId,
  callId: l.callId,
  fromTag: l.fromTag,
  source: l.source,
  state: l.state as Leg["state"],
  disposition: l.disposition as Leg["disposition"],
  dialogs: l.dialogs.map(decodeDialog),
  ...(l.noAnswerTimeoutSec !== undefined ? { noAnswerTimeoutSec: l.noAnswerTimeoutSec } : {}),
  ...(l.byeDisposition !== undefined
    ? { byeDisposition: l.byeDisposition as Leg["byeDisposition"] }
    : {}),
  ...(l.localUri !== undefined ? { localUri: l.localUri } : {}),
  ...(l.remoteUri !== undefined ? { remoteUri: l.remoteUri } : {}),
  ...(l.inviteRequestUri !== undefined ? { inviteRequestUri: l.inviteRequestUri } : {}),
  ...(l.pendingInviteTxnJson !== undefined
    ? { pendingInviteTxn: JSON.parse(l.pendingInviteTxnJson) as Leg["pendingInviteTxn"] }
    : {}),
  ...(l.extJson !== undefined ? { ext: JSON.parse(l.extJson) as Leg["ext"] } : {}),
})

const fromProtoObject = (p: Record<string, unknown>): Call => {
  const out: Record<string, unknown> = {
    callRef: p.callRef,
    aLeg: decodeLeg(p.aLeg as ProtoLeg),
    bLegs: (p.bLegs as ProtoLeg[]).map(decodeLeg),
    aLegInvite: p.aLegInvite,
    limiterEntries: p.limiterEntries,
    timers: p.timers,
    cdrEvents: p.cdrEvents,
    state: p.state,
    createdAt: p.createdAt,
    tagMap: p.tagMap,
    activePeer: p.activePeerIsNull === true ? null : (p.activePeer ?? null),
  }

  if (p.callbackContext !== undefined) out.callbackContext = p.callbackContext
  if (p.billingContextIsNull === true) {
    out.billingContext = null
  } else if (p.billingContext !== undefined) {
    out.billingContext = p.billingContext
  }
  if (p.aLegPendingViasPresent === true) {
    out.aLegPendingVias = (p.aLegPendingVias ?? []) as ReadonlyArray<string>
  }
  if (p.aLegPendingCSeq !== undefined) out.aLegPendingCSeq = p.aLegPendingCSeq
  if (p.traceId !== undefined) out.traceId = p.traceId
  if (p.rootSpanId !== undefined) out.rootSpanId = p.rootSpanId
  if (p.sampled !== undefined) out.sampled = p.sampled
  if (p.workerIndex !== undefined) out.workerIndex = p.workerIndex
  if (p.topology !== undefined) out._topology = p.topology
  if (p.emergency !== undefined) out.emergency = p.emergency

  if (p.featuresJson !== undefined) out.features = JSON.parse(p.featuresJson as string)
  if (p.policyUpdateHeadersJson !== undefined)
    out.policyUpdateHeaders = JSON.parse(p.policyUpdateHeadersJson as string)

  if (p.policyUpdateBodyIsNull === true) {
    out.policyUpdateBody = null
  } else if (p.policyUpdateBody !== undefined) {
    out.policyUpdateBody = p.policyUpdateBody
  }

  if (p.activeRulesPresent === true) {
    const rules = (p.activeRules ?? []) as ReadonlyArray<{
      id: string
      active: boolean
      paramsPresent: boolean
      paramsJson?: string
    }>
    out.activeRules = rules.map((r) => ({
      id: r.id,
      active: r.active,
      ...(r.paramsPresent
        ? { params: r.paramsJson === undefined ? undefined : JSON.parse(r.paramsJson) }
        : {}),
    }))
  }

  if (p.ruleStatePresent === true) {
    const states = (p.ruleState ?? []) as ReadonlyArray<{
      ruleId: string
      statePresent: boolean
      stateJson?: string
    }>
    out.ruleState = states.map((r) => ({
      ruleId: r.ruleId,
      ...(r.statePresent
        ? { state: r.stateJson === undefined ? undefined : JSON.parse(r.stateJson) }
        : {}),
    }))
  }

  if (p.extJson !== undefined) out.ext = JSON.parse(p.extJson as string)

  if (p.messageCount !== undefined) out.messageCount = p.messageCount
  if (p.terminatingRefreshLegsPresent === true) {
    out.terminatingRefreshLegs = (p.terminatingRefreshLegs ?? []) as ReadonlyArray<string>
  }

  return out as unknown as Call
}

// ---------------------------------------------------------------------------
// Codec API
// ---------------------------------------------------------------------------

const makeProtobufImpl = (): CallBodyCodecApi => {
  const encode = (call: Call): Buffer => {
    const obj = toProtoObject(call)
    const msg = CallProto.create(obj)
    const finished = CallProto.encode(msg).finish()
    return Buffer.from(finished.buffer, finished.byteOffset, finished.byteLength)
  }
  const decode = (buf: Buffer): Call => {
    const msg = CallProto.decode(buf)
    const obj = CallProto.toObject(msg, { bytes: Buffer, defaults: false, arrays: true })
    return fromProtoObject(obj)
  }
  return { encode, decode }
}

export const ProtobufLayer: Layer.Layer<CallBodyCodec> = Layer.effect(
  CallBodyCodec,
  Effect.sync(() => makeProtobufImpl()),
)

/** Synchronous factory for tests / one-off use that can't take a Layer. */
export const makeProtobufUnsafe = (): CallBodyCodecApi => makeProtobufImpl()
