/**
 * In-dialog re-INVITE scenarios:
 *
 * 1. aliceReInvite — Alice sends re-INVITE with no SDP (offer in 200 OK, answer in ACK)
 * 2. bobReInvite   — Bob sends re-INVITE with SDP offer
 * 3. crossingReInvite — Both sides send re-INVITE simultaneously (glare → 491)
 */

import { scenario } from "../../src/test-harness/framework/dsl.js"
import { callSetup } from "./bye-directions.js"
import { sdpOffer, sdpAnswer } from "../../src/test-harness/framework/helpers/sdp.js"

// ---------------------------------------------------------------------------
// 1. Alice re-INVITEs Bob — no SDP in re-INVITE, offer in 200 OK, answer in ACK
// ---------------------------------------------------------------------------

const aliceReInviteFragment = scenario("alice-reinvite-fragment", (s) => {
  const alice = s.agent("alice", { uri: "sip:alice@test" })
  const bob = s.agent("bob", { uri: "sip:bob@test", port: 5666 })

  const aliceDialog = alice.dialog
  const bobDialog = bob.dialog

  s.pause(500)

  // Alice sends re-INVITE with no SDP body (delayed offer)
  const aliceReInvTxn = aliceDialog.send("INVITE")

  // Alice receives 100 Trying (auto-generated by TransactionLayer)
  aliceReInvTxn.expect(100)

  // Bob receives re-INVITE (no body)
  const bobReInvTxn = bobDialog.expect("INVITE", {
    predicate: (msg) => !msg.hasBody(),
  })

  // Bob responds 200 OK with SDP offer
  bobReInvTxn.reply(200, {
    overrides: { body: sdpOffer(undefined, 30000) },
  })

  // Alice receives 200 OK with SDP offer
  aliceReInvTxn.expect(200, {
    predicate: (msg) => msg.hasBody(),
  })

  // Alice sends ACK with SDP answer
  aliceDialog.ack({
    build: () => ({ body: sdpAnswer(undefined, { port: 30000 }) }),
  })

  // Bob receives ACK with SDP answer
  bobDialog.expect("ACK", {
    predicate: (msg) => msg.hasBody(),
  })

  // Verify call is still alive — Alice hangs up normally
  s.pause(500)
  const aliceByeTxn = aliceDialog.bye()
  const bobByeTxn = bobDialog.expect("BYE")
  bobByeTxn.reply(200)
  aliceByeTxn.expect(200)
})

export const aliceReInvite = callSetup.andThen(aliceReInviteFragment).title("re-INVITE from caller (SDP in ACK)")

// ---------------------------------------------------------------------------
// 2. Bob re-INVITEs Alice — SDP offer in re-INVITE, answer in 200 OK
// ---------------------------------------------------------------------------

const bobReInviteFragment = scenario("bob-reinvite-fragment", (s) => {
  const alice = s.agent("alice", { uri: "sip:alice@test" })
  const bob = s.agent("bob", { uri: "sip:bob@test", port: 5666 })

  const aliceDialog = alice.dialog
  const bobDialog = bob.dialog

  s.pause(500)

  // Bob sends re-INVITE with SDP offer
  const bobReInvTxn = bobDialog.send("INVITE", {
    overrides: { body: sdpOffer(undefined, 30000) },
  })

  // Bob receives 100 Trying (auto-generated by TransactionLayer)
  bobReInvTxn.expect(100)

  // Alice receives re-INVITE with SDP body
  const aliceReInvTxn = aliceDialog.expect("INVITE", {
    predicate: (msg) => msg.hasBody(),
  })

  // Alice responds 200 OK with SDP answer
  aliceReInvTxn.reply(200, {
    overrides: { body: sdpAnswer(undefined, { port: 30000 }) },
  })

  // Bob receives 200 OK with SDP answer
  bobReInvTxn.expect(200, {
    predicate: (msg) => msg.hasBody(),
  })

  // Bob sends ACK (no SDP — offer/answer already complete)
  bobDialog.ack()

  // Alice receives ACK
  aliceDialog.expect("ACK")

  // Verify call is still alive — Bob hangs up
  s.pause(500)
  const bobByeTxn = bobDialog.bye()
  const aliceByeTxn = aliceDialog.expect("BYE")
  aliceByeTxn.reply(200)
  bobByeTxn.expect(200)
})

export const bobReInvite = callSetup.andThen(bobReInviteFragment).title("re-INVITE from callee")

// ---------------------------------------------------------------------------
// 3. Crossing re-INVITEs (glare) — both sides send re-INVITE simultaneously
//
// Flow:
//   Alice → re-INVITE → B2BUA → relays to Bob
//   Bob   → re-INVITE → B2BUA → detects glare → 491 to Bob
//   Bob   → 200 OK (for Alice's re-INVITE) → relayed to Alice
//   Alice → ACK → relayed to Bob
//   Bob's 491 ACK is absorbed by TransactionLayer (ACK for non-2xx)
// ---------------------------------------------------------------------------

const crossingReInviteFragment = scenario("crossing-reinvite-fragment", (s) => {
  const alice = s.agent("alice", { uri: "sip:alice@test" })
  const bob = s.agent("bob", { uri: "sip:bob@test", port: 5666 })

  const aliceDialog = alice.dialog
  const bobDialog = bob.dialog

  s.pause(500)

  // Alice sends re-INVITE first (this one wins)
  const aliceReInvTxn = aliceDialog.send("INVITE", {
    overrides: { body: sdpOffer(undefined, 30000) },
  })

  // Alice receives 100 Trying (auto-generated by TransactionLayer)
  aliceReInvTxn.expect(100)

  // Bob receives Alice's relayed re-INVITE
  const bobReInvUasTxn = bobDialog.expect("INVITE")

  // Bob also sends his own re-INVITE (before responding to Alice's).
  // This one loses the glare race and is rejected 491 — no answer expected.
  const bobReInvTxn = bobDialog.send("INVITE", {
    overrides: { body: sdpOffer(undefined, 40000) },
    skipValidation: ["offerAnswer"],
  })

  // Bob receives 100 Trying for his re-INVITE (auto-generated), then 491 (glare)
  bobReInvTxn.expect(100)
  bobReInvTxn.expect(491)

  // Bob responds 200 OK to Alice's re-INVITE
  bobReInvUasTxn.reply(200, {
    overrides: { body: sdpAnswer(undefined, { port: 30000 }) },
  })

  // Alice receives 200 OK
  aliceReInvTxn.expect(200, {
    predicate: (msg) => msg.hasBody(),
  })

  // Alice sends ACK
  aliceDialog.ack()

  // Bob receives ACK (the real one for Alice's re-INVITE, not for the 491)
  bobDialog.expect("ACK")

  // Call is still alive — tear down
  s.pause(500)
  const aliceByeTxn = aliceDialog.bye()
  const bobByeTxn = bobDialog.expect("BYE")
  bobByeTxn.reply(200)
  aliceByeTxn.expect(200)
})

export const crossingReInvite = callSetup.andThen(crossingReInviteFragment).title("crossing re-INVITEs (glare → 491)")
