/**
 * Route-set propagation scenario — proxy+b2b only.
 *
 * Asserts the RFC 3261 §12 / §16.12 mechanic the proxy+b2b SUT depends on:
 *
 *   1. **A-leg ingress (proxy → worker)**: the proxy inserts a stickiness
 *      Record-Route on Alice's INVITE.
 *   2. **A-leg response (worker → proxy → alice)**: the worker reflects
 *      that Record-Route on the dialog-creating 2xx so Alice can build
 *      her route set.
 *   3. **A-leg in-dialog (alice → proxy → worker)**: Alice's BYE carries
 *      a `Route` header that the proxy can decode back to the originating
 *      worker (cookie-decode path), instead of falling back to
 *      `selectForNewDialog` for every in-dialog request.
 *   4. **B-leg egress (worker → proxy → bob)**: the worker pre-loads
 *      `Route: <sip:proxy:port;lr;outbound>` and addresses the packet to
 *      the proxy. The proxy strips the top Route, identifies the source
 *      worker, inserts a Record-Route encoding *that* worker, and forwards
 *      to Bob. Bob's view: INVITE carries the proxy's Record-Route.
 *
 * Ahead of Slice B's worker fix the 100 Trying happens to carry R-R
 * (TransactionLayer copies request headers verbatim), but the 180/200
 * generated by the rule framework do not. Hence this scenario is the
 * red-test for that gap.
 *
 * Out of scope here:
 *   - Bob-initiated BYE / re-INVITE — covered indirectly when the basic
 *     loose-route flow lands on both legs.
 */

import { scenario } from "../fullcall/framework/dsl.js"
import { sdpOffer, sdpAnswer } from "../fullcall/helpers/sdp.js"
import type { SipHeader } from "../../src/sip/types.js"

function getHeader(headers: ReadonlyArray<SipHeader>, name: string): string | undefined {
  return headers.find((h) => h.name.toLowerCase() === name.toLowerCase())?.value
}

function isProxyStickinessRR(value: string | undefined): boolean {
  if (value === undefined) return false
  // proxy advertises 127.0.0.1:15060 with v2 cookie params w_pri=, w_bak=,
  // kid=, sig=, lr (cookie format v2 — D8 of HA-resilience plan).
  return (
    value.includes("127.0.0.1:15060") &&
    /;w_pri=/.test(value) &&
    /;w_bak=/.test(value) &&
    /;sig=/.test(value) &&
    /;lr/.test(value)
  )
}

export const routeSetPropagation = scenario("route-set-propagation", (s) => {
  const alice = s.agent("alice", { uri: "sip:alice@test" })
  const bob = s.agent("bob", { uri: "sip:bob@test", port: 5666 })

  const { dialog: aliceDialog, transaction: aliceInviteTxn } = alice.invite(
    "sip:+1234@127.0.0.1:15060",
    { body: sdpOffer() },
  )

  // (1) + (4): Bob receives the B-leg INVITE *via the proxy* — must carry
  // a proxy-stamped Record-Route so Bob's UAS-side route set decodes back
  // to the originating worker on subsequent in-dialog requests.
  const { dialog: bobDialog, transaction: bobInviteTxn } = bob.receiveInitialInvite({
    predicate: (msg) => isProxyStickinessRR(getHeader(msg.headers, "record-route")),
  })

  // 100 Trying may or may not carry R-R; not load-bearing here.
  aliceInviteTxn.expect(100)

  bobInviteTxn.reply(180)
  // (2): Alice's dialog-creating provisional with to-tag must carry R-R
  // (RFC 3261 §12.1.2 — this is what Alice reverses into her route set).
  aliceInviteTxn.expect(180, {
    predicate: (msg) => isProxyStickinessRR(getHeader(msg.headers, "record-route")),
  })

  bobInviteTxn.reply(200, { body: sdpAnswer() })
  aliceInviteTxn.expect(200, {
    predicate: (msg) => isProxyStickinessRR(getHeader(msg.headers, "record-route")),
  })

  aliceDialog.ack()
  // (3): proxy strips top Route on the way through; Bob's worker-side
  // ACK arrives without that Route. (The B-leg ACK is built by the
  // worker from the B-leg dialog state — no proxy cookie on it.)
  bobDialog.expect("ACK", {
    predicate: (msg) => {
      const route = getHeader(msg.headers, "route")
      return route === undefined || !isProxyStickinessRR(route)
    },
  })

  s.pause(1000)

  const aliceByeTxn = aliceDialog.bye()
  bobDialog.expect("BYE", {
    predicate: (msg) => {
      const route = getHeader(msg.headers, "route")
      return route === undefined || !isProxyStickinessRR(route)
    },
  }).reply(200)
  aliceByeTxn.expect(200)
}).runOn(["proxy+b2b"])
