{{- if or .Values.hmacKey .Values.previousHmacKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sip-front-proxy.fullname" . }}-hmac
  labels:
    {{- include "sip-front-proxy.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.hmacKey }}
  current: {{ .Values.hmacKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.previousHmacKey }}
  previous: {{ .Values.previousHmacKey | b64enc | quote }}
  {{- end }}
{{- end -}}
