apiVersion: v1
kind: Service
metadata:
  name: {{ include "sip-front-proxy.fullname" . }}
  labels:
    {{- include "sip-front-proxy.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "sip-front-proxy.selectorLabels" . | nindent 4 }}
  ports:
    - name: sip-udp
      protocol: UDP
      port: {{ .Values.bind.port }}
      targetPort: {{ .Values.bind.port }}
