{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sip-front-proxy.serviceAccountName" . }}
  labels:
    {{- include "sip-front-proxy.labels" . | nindent 4 }}
{{- end -}}
